### PR TITLE
Setup CI

### PR DESCRIPTION
**Pull request by Hardcode84**
* Setup CI based on github actions
* Add `--ignore-errors` option to  `run_framework.py` to allow return errors from runs instead of silently ignoring them
* Only test Numba for now
* Some Numba benchmarks are failing to compile/validate at the moment

### CODE REVIEW

**Comment by Hardcode84** [comment]
Hmm, it seems it need something else to be setup on project side (github actions it worked out of the box on my fork)

**Comment by alexnick83** [comment]
> Hmm, it seems it need something else to be setup on project side (github actions it worked out of the box on my fork)

It probably needs to be done on the main project. I will try to fix it and update you.

**Comment by Hardcode84** [comment]
Any update on this?

**Comment by alexnick83** [comment]
> Any update on this?

Sorry for the delay. I pushed your changes to a new PR (#4), which now triggers the CI. I will probably make it, so the workflow doesn't "fail" as long as the project's code isn't the cause of the exception and then merge. Thank you for contributing!

**Pull request merged**
